name: stationery_app
description: A new Flutter project

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.3.0
  firebase_database: ^11.1.0
  geolocator: ^13.0.0
  geocoding: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/