// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6a4P5HMLpi1qNoyMCIDBtnY2SjZFmgdA',
    appId: '1:601250993481:web:01342f93d45750e0423698',
    messagingSenderId: '601250993481',
    projectId: 'stationaryapp-36116',
    authDomain: 'stationaryapp-36116.firebaseapp.com',
    databaseURL: 'https://stationaryapp-36116-default-rtdb.firebaseio.com',
    storageBucket: 'stationaryapp-36116.firebasestorage.app',
    measurementId: 'G-JL728KXYJZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNQcvNUjNF_xgk6c8SYoQf6lPP7J2QMIQ',
    appId: '1:601250993481:android:b6aa911917e13dbc423698',
    messagingSenderId: '601250993481',
    projectId: 'stationaryapp-36116',
    databaseURL: 'https://stationaryapp-36116-default-rtdb.firebaseio.com',
    storageBucket: 'stationaryapp-36116.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRAgBGQk_FsEoF2kneLJaZr8PaY5hesgQ',
    appId: '1:601250993481:ios:aab157b52bb97b0f423698',
    messagingSenderId: '601250993481',
    projectId: 'stationaryapp-36116',
    databaseURL: 'https://stationaryapp-36116-default-rtdb.firebaseio.com',
    storageBucket: 'stationaryapp-36116.firebasestorage.app',
    iosBundleId: 'com.example.stationeryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRAgBGQk_FsEoF2kneLJaZr8PaY5hesgQ',
    appId: '1:601250993481:ios:aab157b52bb97b0f423698',
    messagingSenderId: '601250993481',
    projectId: 'stationaryapp-36116',
    databaseURL: 'https://stationaryapp-36116-default-rtdb.firebaseio.com',
    storageBucket: 'stationaryapp-36116.firebasestorage.app',
    iosBundleId: 'com.example.stationeryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6a4P5HMLpi1qNoyMCIDBtnY2SjZFmgdA',
    appId: '1:601250993481:web:136e3eb920a34d1e423698',
    messagingSenderId: '601250993481',
    projectId: 'stationaryapp-36116',
    authDomain: 'stationaryapp-36116.firebaseapp.com',
    databaseURL: 'https://stationaryapp-36116-default-rtdb.firebaseio.com',
    storageBucket: 'stationaryapp-36116.firebasestorage.app',
    measurementId: 'G-Q9FTZVZDW1',
  );
}
